### ISSUE TITLE
索要csl文本摘要数据集

### ISSUE THREAD

**Issue by VeraRyan** [ydli-ai/CSL#1]
您所分享的csl文本摘要数据集已取消百度网盘分享，能否再发起一次分享？

**Comment by P01son6415** [comment]
链接: https://pan.baidu.com/s/1_0Vv4LYbq8PchWpJu3E-IA 提取码: sr5p


________________________________
发件人: 敲鸡牛逼的浅浅 <notifications@github.com>
发送时间: 2020年7月6日 23:07
收件人: P01son6415/CSL <CSL@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [P01son6415/CSL] 索要csl文本摘要数据集 (#1)


您所分享的csl文本摘要数据集已取消百度网盘分享，能否再发起一次分享？

―

**Comment by VeraRyan** [comment]
感谢您的分享

**Comment by LowinLi** [comment]
又过期了

**Comment by ydli-ai** [comment]
> 又过期了

数据集及代码正在整理中，预计7月会重新公开
